export const GenresConstants = [
    { "id": 2, "name": "Point-and-click" },
    { "id": 4, "name": "Luta" },
    { "id": 5, "name": "Tiro" },
    { "id": 7, "name": "Música" },
    { "id": 8, "name": "Plataforma" },
    { "id": 9, "name": "Quebra-cabeça" },
    { "id": 10, "name": "Corrida" },
    { "id": 11, "name": "Estratégia em Tempo Real (RTS)" },
    { "id": 12, "name": "RPG (Jogo de Interpretação de Papéis)" },
    { "id": 13, "name": "Simulador" },
    { "id": 14, "name": "Esportes" },
    { "id": 15, "name": "Estratégia" },
    { "id": 16, "name": "Estratégia por Turnos (TBS)" },
    { "id": 24, "name": "Tático" },
    { "id": 25, "name": "Hack and Slash/Beat 'em up" },
    { "id": 26, "name": "Quiz/Trivia" },
    { "id": 30, "name": "Pinball" },
    { "id": 31, "name": "Aventura" },
    { "id": 32, "name": "Indie (Independente)" },
    { "id": 33, "name": "Arcade" },
    { "id": 34, "name": "Visual Novel" },
    { "id": 35, "name": "Jogo de Cartas e Tabuleiro" },
    { "id": 36, "name": "MOBA (Multiplayer Online Battle Arena)" }
]
